from typing import Optional

def core_version() -> str: ...
def discover(root: Optional[str] = None, config_path: Optional[str] = None) -> list[str]: ...
def scan_json(root: Optional[str] = None, config_path: Optional[str] = None) -> str: ...
